## OTUS: Basic ML
### Модуль 4. Теоретический минимум для ML: линейная алгебра, начала мат.анализа и оптимизации, статистика.
#### Линейная алгебра

In [1]:
import numpy as np

#### 1. Посчитайте матрицу D = A$^{T}$C − 2A$^{T}$B$^{T}$. Приведите полную последовательность вычислений.

In [2]:
A = np.array([[2,-4],
              [3 ,5 ],
              [-1,0 ]])

B = np.array([[1 ,2 ,7 ],
              [-3,-4,0 ],
              [5 ,2 ,1 ]])


C = np.array([[6 ,-3,9 ],
              [4 ,-5,2 ],
              [8 ,1 ,5 ]])

# Последовательность вычислений:
# Транспонировать B       -> BT
# Вычесть из С BT 2 раза  -> D
# Транспонировать А       -> AT
# Умножить AT на D        -> D
D1 = A.T@(C-2*B.T)

print('Результат вычислений:\n', D1)

Результат вычислений:
 [[ 14  14 -11]
 [-16   3  -6]]


#### 2. Найдите значения x, y, z и v, при которых выражение верно.

In [3]:
# 3*A+2*B=C

# A = np.array([[x,2,3],
#               [-1,y,4]])

# B = np.array([[1,2,-5],
#               [2,-6,z]])

# C = np.array([[8,v,-1],
#               [1,6,4]])

# Порядок вычислений
# 3*x+2*1=8
# 3*2+2*2=v
# 3*y+2*(-6)=6
# 3*4+2*z=4x=2

x=2
y=6
z=-4
v=10

A = np.array([[x,2,3],
              [-1,y,4]])

B = np.array([[1,2,-5],
              [2,-6,z]])

C = np.array([[8,v,-1],
              [1,6,4]])


D=3*A+2*B-C

print('Результат вычислений:\n', D, f'\n при x={x} , y={y} , z={z} , v={v}')

Результат вычислений:
 [[0 0 0]
 [0 0 0]] 
 при x=2 , y=6 , z=-4 , v=10


#### 3. Укажите те значения параметров p и q, при которых ранг матрицы равен единице
_Рангом матрицы называется максимальное число линейно независимых строк (столбцов) этой матрицы._

In [4]:
p=9
q=15

M = np.array([[1,2,3],
              [3,6,p],
              [5,10,q],])

result=np.linalg.matrix_rank(M)

print(f'Ранг матрицы равен {result} при p={p} , q={q}')

Ранг матрицы равен 1 при p=9 , q=15


#### 4. Задача
Относительно канонического (стандартного) базиса в R$^{2}$ даны три вектора a$_{1}$ = (2, −5)$^{T}$, a$_{2}$ = (−1, 3)$^{T}$ и x = (1, −4)$^{T}$. Примите векторы a$_{1}$, a$_{2}$ за новый базис B, предварительно проверив, что они линейно
независимы.

4. (a) Найдите координаты [x]$_{B}$ вектора x в новом базисе.
4. (b) Предположим, что координаты вектора y в базисе B заданы [y]$_{B}$ = (1, 1)$^{T}$. Найдите координаты вектора y в стандартном базисе.

In [5]:
strDel="\n-------------------------------"
print("Дано:")
a1 = np.array([[2,-5]]).T
a2 = np.array([[-1, 3]]).T
x = np.array([[1,-4]]).T
y = np.array([[1, 1]]).T
print("a1:",a1)
print("a2:",a2)
print("x:",x)
print("y:",y)
print(strDel)

# Векторы образуют базис, если определитель, составленный из координат этих векторов, отличен от нуля
M =np.hstack((a1,a2))
result=np.linalg.det(M)
print(f'Векторы a1 и a2 образуют базис: {result!=0}',strDel)

# (1;-4) = (2α;-5a) + (-1b;3b)
# (1;-4) = (2α - 1b ; -5α + 3b)
# a= -1 , b= -3
result=np.linalg.inv(np.column_stack((a1, a2))).dot(x)
print("Координаты вектора [x]𝐵 в базисе a1,a2:")
print(result, strDel)


# (y1;y2) = (2;-5) + (-1;3)
# (y1;y2) = (2 - 1 ; -5 + 3)
# y1= 1 , y2= -2
print("Координаты вектора y в стандартном базисе:")
print(np.array([[1,-2]]).T)


Дано:
a1: [[ 2]
 [-5]]
a2: [[-1]
 [ 3]]
x: [[ 1]
 [-4]]
y: [[1]
 [1]]

-------------------------------
Векторы a1 и a2 образуют базис: True 
-------------------------------
Координаты вектора [x]𝐵 в базисе a1,a2:
[[-1.]
 [-3.]] 
-------------------------------
Координаты вектора y в стандартном базисе:
[[ 1]
 [-2]]


## Начала мат.анализа и оптимизации

### 1. Задача

Посчитайте матрицу Гессе следующей функции:
f(x) = x$^{3}_{1}$ − 2x$_{1}$x$_{2}$ + x$^{2}_{2}$ − 3x$_{1}$ − 2x$_{2}$, x ∈ R$^{2}$.

Найдите критические точки x$_{c}$, такие что ∇f(x$_{c}$) = 0.

### Решение
1. Найдем частные производные.

$∂f(x) \over ∂x_1$= 3x$_{1}^{2}$-2x$_{2}$-3

$∂f(x) \over ∂x_2$= -2x$_{1}$+2x$_{2}$-2

2. Найдем частные производные второго порядка.

$∂^2f(x) \over ∂x^2_1$= 6x$_{1}$  ,  $∂^2f(x) \over ∂x_2∂x_1$= -2

 $∂^2f(x) \over ∂x_1∂x_2$= -2  ,  $∂^2f(x) \over ∂x^2_2$= 2
 
<hr>
Матрица Гессе:

$\begin{vmatrix} 6x_{1} & -2  \\ -2 & 2  \end{vmatrix}$
 
<hr>

3. Найдем x$_{c}$, такие что ∇f(x$_{c}$) = 0

$\begin{equation}
\left\{ \begin{aligned} 
3x_1^2-2x_2-3 = 0 \\
-2x_1+2x_2-2 = 0
\end{aligned} \right.
\end{equation}$
 
<hr>
$x_c$ (-1;0)

$x_c  (\frac{5}{3};\frac{8}{3})$ 

<hr>

### 2. Задача

Проверьте, что функция $f(x) = ln(\sqrt{x_1}+\sqrt{x_2})$ удовлетворяет уравнению:

$x_1 \frac{∂f}{∂x_1} + x_2 \frac{∂f}{∂x_2}= \frac{1}{2} $

### Решение
1. Найдем частные производные.

$\frac{∂f}{∂x_1}= \frac{1}{2\sqrt{x_1}\Bigl(\sqrt{x_1}+\sqrt{x_2}\Bigr) } $

$\frac{∂f}{∂x_2}= \frac{1}{2\sqrt{x_2}\Bigl(\sqrt{x_1}+\sqrt{x_2}\Bigr) } $

2. Решим уравнение.

$x_1 \frac{∂f}{∂x_1} + x_2 \frac{∂f}{∂x_2}= \frac{1}{2} \Bigl(\frac{x_1}{\sqrt{x_1}\Bigl(\sqrt{x_1}+\sqrt{x_2} \Bigr)} + \frac{x_2}{\sqrt{x_2}\Bigl(\sqrt{x_1}+\sqrt{x_2} \Bigr)}\Bigr)= $ 

$= \frac{1}{2} \Bigl(\frac{\sqrt{x_1}}{\Bigl(\sqrt{x_1}+\sqrt{x_2} \Bigr)} + \frac{\sqrt{x_2}}{\Bigl(\sqrt{x_1}+\sqrt{x_2} \Bigr)}\Bigr) = \frac{1}{2}$

### 3. Задача

Предположим, задана функция $f : R^3 → R^2$

$f(x, y, z) = (x + y + z, xyz)^⊤ $

Найдите матрицу Якоби $J_f$ функции $f$, и её численное значение в точке $v = (1, 2, 3)^⊤$

### Решение
1. Найдем вид матрицы Якоби $J_f$.

$\begin{vmatrix} \frac{∂f_1}{∂x} & \frac{∂f_1}{∂y} & \frac{∂f_1}{∂z} \\
\frac{∂f_2}{∂x} & \frac{∂f_2}{∂y} & \frac{∂f_2}{∂z}
\end{vmatrix}$ =

= $\begin{vmatrix} 1 & 1 & 1 \\
yz & xz & xy
\end{vmatrix}$

2. $J_f$ в точке $v = (1, 2, 3)^⊤$.

$\begin{vmatrix} 1 & 1 & 1 \\
6 & 3 & 2
\end{vmatrix}$

### 4. Задача
Найти первый и второй дифференциалы $∂f(x)$ и $∂^2f(x)$, а также градиент $∇f(x)$ и гессиан $∇^2f(x)$ функции:

$f(x) = \frac{1}{3}||x||^3_2, x ∈ R^n$ \ {0}.

### Решение
1. Найдем ∂𝑓(𝑥).

$f(x) = f(g(x)) = \frac{1}{3}||x||^3_2 = \frac{1}{3}\Bigl(\sum_{i=0}^{n}{x^2_i}\Bigr)^3$

$f(x) = \frac{1}{3}||x||^3_2 = \frac{1}{3}(g(x))^3$

$g(x) = ||x|| $

$∂f(x) =   $

$g(x) = \sum_{i=0}^{n}{x^2_i} $

